### ISSUE TITLE
Issues Using PuffOS

### ISSUE THREAD

**Issue by AmazinAxel** [electrikmilk/Puff-OS#1]
Hi! I am trying to use Puff OS on my webserver and I am running into some issues. Some things are not loading, and the console shows many errors. I enabled the debug options in PHP to see what warnings / errors there were in PHP, and there were many undefined array keys, variables, etc. I am wondering how to fix these issues and what I should be using, such as a specific PHP version (I have tested it with PHP 8.0 and 7.1.3) or if there is anything that I am missing. I have tried clearing the cache, putting all the files in the root directory among other things. I am happy to send you some debug info (stuff from the console, PHP errors, etc.) Thanks for your help!

**Comment by electrikmilk** [comment]
Thanks for your interest in Puff OS!

The latest commit seeks to fix a lot of the major issues. Some minor issues may still remain.

PHP 7.4 is recommended for now.

**Comment by AmazinAxel** [comment]
Hi! Thanks for your response. The new version seems to be working a bit better as I am now able to log in and use some of the features of Puff OS. I have ran into a couple issues, such as the file manager showing a blank screen, but I understand that this is a early version. Overall, this update really helped fix many issues. Thanks for this update and keep up your great work!
